name: Deploy ConfigMap to Git

on:
  push:
    paths:
      - 'application/hello.html'  # 이 파일이 변경되면 실행
    branches:
      - main

jobs:
  generate-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate ConfigMap from HTML
        run: |
          mkdir -p manifests
          echo "apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
  namespace: jhhan
data:
  hello.html: |" > manifests/hello-config.yaml
          sed 's/^/    /' application/hello.html >> manifests/hello-config.yaml
          
      - name: Commit & Push
        run: |
          git config user.name "jhhan-github-actions"
          git config user.email "jhhan-actions@github.com"
          git add manifests/hello-config.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update ConfigMap from hello.html"
            git push
          fi

