name: Deploy ConfigMap to Git

on:
  push:
    paths:
      - 'application/hello.html'
    branches:
      - main

jobs:
  generate-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate ConfigMap from HTML
        run: |
          mkdir -p manifests/tomcat
          {
            echo "apiVersion: v1"
            echo "kind: ConfigMap"
            echo "metadata:"
            echo "  name: hello-html"
            echo "  namespace: jhhan"
            echo "data:"
            echo "  hello.html: |"
            sed 's/^/    /' application/hello.html
          } > manifests/tomcat/hello-configmap.yaml

      - name: Commit & Push
        run: |
          git config user.name "jhhan-github-actions"
          git config user.email "jhhan-actions@github.com"
          git add manifests/tomcat/hello-configmap.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update ConfigMap from hello.html"
            git push
          fi
